version: '3.8'
services:
  db:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_DB: spareit
      POSTGRES_USER: spareit
      POSTGRES_PASSWORD: spareit
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql:ro
  app:
    build: .
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://spareit:spareit@db:5432/spareit
      PORT: 3000
    ports:
      - '3000:3000'
    command: ["node", "index.js"]
    restart: always
    volumes:
      - .:/app:rw
volumes:
  pgdata:
